### PR TITLE
Fix http2 and metrics

### LINKED ISSUE #172: Metrics endpoint is not returning correct value
### Summary
the `/metrics/` endpoint is not returning the correct value. For HTTP/2 requests, the response is invalid. For http/1.1 it returns the metrics module name.

### Steps to reproduce
$ curl -k https://localhost:8080/metrics -vvv (for http 2)
$ curl -k https://localhost:8080/metrics -vvv --http1.1

### Expected behavior
Should return the metrics as collected in JSON format.

### Actual behavior
```shell
$ curl -k https://localhost:8080/metrics -vvv
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=IL; L=Chicago; O=xio2; OU=dev; CN=xio2.example.com
*  start date: Aug 12 19:35:09 2015 GMT
*  expire date: Jun  1 19:35:09 2018 GMT
*  issuer: C=US; ST=IL; L=Chicago; O=xio2; OU=dev; CN=xio2.example.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd03b80b000)
> GET /metrics HTTP/2
> Host: localhost:8080
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer:
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
* Failed receiving HTTP2 data
* Connection #0 to host localhost left intact
curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

$ curl -k https://localhost:8080/metrics -vvv --http1.1
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /usr/local/etc/openssl/cert.pem
  CApath: /usr/local/etc/openssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=IL; L=Chicago; O=xio2; OU=dev; CN=xio2.example.com
*  start date: Aug 12 19:35:09 2015 GMT
*  expire date: Jun  1 19:35:09 2018 GMT
*  issuer: C=US; ST=IL; L=Chicago; O=xio2; OU=dev; CN=xio2.example.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /metrics HTTP/1.1
> Host: localhost:8080
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer:
>
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 86
<
{
  "moduleName" : "metrics",
  "typeId" : "com.codahale.metrics.json.MetricsModule"
* Connection #0 to host localhost left intact
}
```

### Minimal yet complete reproducer code (or URL to code)
(see above) 

### xrpc version
git master as of March, 10 2018

### PR DESCRIPTION
**Pull request by andyday**
Fixes #172 

- Fix broken http2 access for demos/people.  NullPointer exception in Http2CorsHandler.
- Fix /metrics access for demos/people.  We were passing the MetricsModule not MetricsRegistry to encoding.
- Add alpn support for OkHttp for testing http2.
- Add sanity unit tests for metrics.
- Changed AdminHandlers to use ResponseFactory methods.
- Added pretty option to Encoder - for use with current AdminHandlers.
- Upgraded gradle to 4.6 - part of attempt to get alpn working.

### CODE REVIEW

File: bin/startPeopleTestServer.sh [hunk 1]
```diff
@@ -4,7 +4,7 @@ set -e
 
 PORT=8080
 
-./gradlew clean shadowJar && \
+./gradlew :demos:people:clean :xrpc:clean :xrpc:compileJava :demos:people:shadowJar && \
```
Comment (jkinkead) [inline bin/startPeopleTestServer.sh]: I would remove these `clean` calls altogether - but they're fairly harmless.

File: xrpc-testing/src/main/java/com/nordstrom/xrpc/testing/UnsafeHttp.java [hunk 2]
```diff
@@ -3,41 +3,48 @@
...
+      OkHttpClient.Builder builder =
           new OkHttpClient.Builder()
               .sslSocketFactory(sslSocketFactory, trustManager)
-              .hostnameVerifier((hostname, session) -> true)
-              .build();
+              .hostnameVerifier((hostname, session) -> true);
 
-      return okHttpClient;
+      if (protocols.length > 0) {
+        // This defaults to http2, http1.1
```
Comment (jkinkead) [inline xrpc-testing/src/main/java/com/nordstrom/xrpc/testing/UnsafeHttp.java]: Maybe hoist to a javadoc comment on the method? It's a little confusing here, because it's documenting the `else`-case.

File: xrpc/src/main/java/com/nordstrom/xrpc/encoding/Encoder.java [hunk 3]
```diff
@@ -32,9 +32,11 @@
    * @param buf target byte buffer for encoding
    * @param acceptCharset Accept-Charset header
    * @param object object to encode
+   * @param pretty if true, attempt to encode with pretty formatting
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/encoding/Encoder.java]: Hmm. This seems so JSON-specific.

I find this a weird place to put this, but I don't know where else it would fit without a redesign.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java [hunk 4]
```diff
@@ -53,42 +53,48 @@ public Http2CorsHandler(CorsConfig config) {
...
+
+        response =
+            new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.INTERNAL_SERVER_ERROR);
+      }
 
-    return Optional.of(response);
+      return Optional.of(response);
+    } catch (Exception e) {
+      log.error("Error handling CORS inbound", e);
+      return Optional.empty();
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: We should be returning a 500 like a few lines above.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java [hunk 5]
```diff
@@ -53,42 +53,48 @@ public Http2CorsHandler(CorsConfig config) {
...
+      } catch (Http2Exception e) {
+        log.error("Error in handling CORS headers.", e);
+
+        response =
+            new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.INTERNAL_SERVER_ERROR);
+      }
 
-    return Optional.of(response);
+      return Optional.of(response);
+    } catch (Exception e) {
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: This should be `RuntimeException` (or be removed entirely in favor of a theoretically-working outer exception handler).

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java [hunk 6]
```diff
@@ -133,20 +139,20 @@ private Http2Headers preflightHeaders(HttpMethod requestMethod) {
   }
 
   /** True if the given origin is allowed based on the CORS configuration. */
-  private boolean validateOrigin(String origin) {
+  private boolean validateOrigin() {
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: Revert back to purer function? If not, the javadoc needs to change.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java [hunk 7]
```diff
@@ -16,50 +16,96 @@
...
     return createResponse(HttpResponseStatus.INTERNAL_SERVER_ERROR, body);
   }
 
+  /**
+   * Return http response with status and body.
+   *
+   * @param status http status
+   * @param body body object to be encoded based on Content Negotiation
+   * @param <T> type of body object
+   * @return HttpResponse
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java]: Remove line?

File: xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java [hunk 8]
```diff
@@ -16,50 +16,96 @@
...
   }
 
+  /**
+   * Return http response with status, body, content type, and custom headers.
+   *
+   * @param status https status
+   * @param body body ByteBuf
+   * @param contentType content type of response
+   * @param customHeaders if non-null these headers will be added to the response
+   * @return HttpResponse
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java]: Remove line?

File: xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java [hunk 9]
```diff
@@ -16,50 +16,96 @@
...
+   */
   default HttpResponse createResponse(
       HttpResponseStatus status, ByteBuf body, CharSequence contentType) {
     return createResponse(status, body, contentType, null);
   }
 
+  /**
+   * Return http response with status, body, content type, and custom headers.
+   *
+   * @param status https status
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java]: Typo (`https` instead of `http`).

File: xrpc/src/main/java/com/nordstrom/xrpc/server/XrpcRequest.java [hunk 10]
```diff
@@ -111,10 +111,26 @@ public XrpcRequest request() {
...
   public ResponseFactory response() {
-    if (responseFactory == null) {
-      responseFactory = () -> XrpcRequest.this;
-    }
-    return responseFactory;
+    return response(false);
+  }
+
+  public ResponseFactory response(boolean pretty) {
+    return new ResponseFactory() {
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/XrpcRequest.java]: `responseFactory` field is now unused and should be deleted.

**Comment by andyday** [comment]
@jkinkead i removed the pretty encoding.  i had originally thought to go that way but added it in anyway.  much cleaner with it gone.  all other comments have been addressed also.

File: bin/startPeopleTestServer.sh [hunk 11]
```diff
@@ -4,7 +4,7 @@ set -e
 
 PORT=8080
 
-./gradlew clean shadowJar && \
+./gradlew :xrpc:compileJava :demos:people:shadowJar && \
```
Comment (manimaul) [inline bin/startPeopleTestServer.sh]: FWIW you don't need the compileJava task ... shadowJar already inherits that

Comment (andyday) [reply bin/startPeopleTestServer.sh]: You would think so but that’s not what I I’m seeing in practice.  I find myself having to rebuild xrpc for the shadowJar to pick up these changes.

Comment (jkinkead) [reply bin/startPeopleTestServer.sh]: Maybe `shadowJar` isn't invalidating its cache when local subproject dependencies change their jar output?

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java [hunk 12]
```diff
@@ -53,42 +53,50 @@ public Http2CorsHandler(CorsConfig config) {
...
+      } catch (Http2Exception e) {
+        log.error("Error in handling CORS headers.", e);
 
-    return Optional.of(response);
+        response =
+            new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.INTERNAL_SERVER_ERROR);
+      }
+
+      return Optional.of(response);
+    } catch (Exception e) {
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: This should be `RuntimeException`.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java (hunk 6 above)
Comment (jkinkead) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: Ping.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java (hunk 7 above)
Comment (jkinkead) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java]: Ping.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java (hunk 9 above)
Comment (jkinkead) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java]: Ping.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java (hunk 8 above)
Comment (jkinkead) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/ResponseFactory.java]: Ping.

File: xrpc/src/test/java/com/nordstrom/xrpc/server/Http2HandlerTest.java [hunk 13]
```diff
@@ -424,7 +424,27 @@ public void testOnHeadersRead_preflightOptionsRequest() {
 
   /** Test that OPTIONS request short circuit to preflight response. */
   @Test
-  public void testOnHeadersRead_corsShortCircuit() {
+  void testOnHeadersRead_noOrigin() {
```
Comment (jkinkead) [inline xrpc/src/test/java/com/nordstrom/xrpc/server/Http2HandlerTest.java]: Update comment on test?

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java (hunk 12 above)
Comment (andyday) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: if netty the uncaught exception is not properly being caught, it could include more than just RuntimeException...

**Comment by andyday** [comment]
on the validateOrigin, if its doing something with the class member variable, i see no reason to pass it in as an argument other than to achieve some sort of functional purity.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java (hunk 12 above)
Comment (jkinkead) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/Http2CorsHandler.java]: Only if something we're calling is using `sneakyThrows` or its equivalent. The compiler guarantees that all checked exceptions are caught.

**Comment by andyday** [comment]
@jkinkead i've addressed these last comments.

File: xrpc/src/main/java/com/nordstrom/xrpc/server/AdminHandlers.java [hunk 14]
```diff
@@ -179,33 +177,24 @@
...
+  public static Handler createMetricsHandler(MetricRegistry metrics) {
+    return request -> request.ok(metrics);
   }
 
   /**
    * Simple ping handler, indicating that the service is up. This returns a a returns a `200 OK`
    * with `PONG` body.
    */
-  public static Handler pingHandler = xrpcRequest -> Recipes.newResponseOk("PONG");
+  public static Handler pingHandler = request -> request.ok("PONG");
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/AdminHandlers.java]: I'm loving the cleaner API every time I look at this PR. :)
