### PR TITLE
Remove scheduled health check runner

### LINKED ISSUE #134: Health Check Warning and Regression Degradation
Per @xjdr 

i am starting to see this error throw every so often now
we also appear to added a bit of a speed regression somewhere is the last few commits
small one, but it appears to be consistent

```
15215088 [xrpc-worker-0] WARN  c.c.m.h.HealthCheckRegistry - Error executing health check simple
io.netty.util.concurrent.BlockingOperationException: PromiseTask@600f6080(incomplete, task: com.codahale.metrics.health.HealthCheckRegistry$1@63103e65)
    at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:391)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:226)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:34)
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
    at com.codahale.metrics.health.HealthCheckRegistry.runHealthChecks(HealthCheckRegistry.java:193)
    at com.nordstrom.xrpc.server.Router.lambda$scheduleHealthChecks$0(Router.java:134)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:131)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:273)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by andyday**
fixes #134

### CODE REVIEW

File: xrpc/src/main/java/com/nordstrom/xrpc/server/Server.java [hunk 1]
```diff
@@ -96,7 +95,7 @@ private Server(XConfig config, int port) {
     this.config = config;
     this.port = port >= 0 ? port : config.port();
     this.tls = new Tls(config.cert(), config.key());
-    this.healthCheckRegistry = new HealthCheckRegistry(config.asyncHealthCheckThreadCount());
+    this.healthCheckRegistry = new HealthCheckRegistry();
```
Comment (jkinkead) [inline xrpc/src/main/java/com/nordstrom/xrpc/server/Server.java]: The zero-args constructor [still creates a thread pool](https://github.com/dropwizard/metrics/blob/600b6c515267c44f191299b9e78801fdebd52b4d/metrics-healthchecks/src/main/java/com/codahale/metrics/health/HealthCheckRegistry.java#L53-L55).

You should retain the `async_health_check_thread_count` setting and logic.

Comment (andyday) [reply xrpc/src/main/java/com/nordstrom/xrpc/server/Server.java]: fixed

File: xrpc/src/main/resources/com/nordstrom/xrpc/xrpc.conf [hunk 2]
```diff
@@ -36,6 +33,7 @@ worker_thread_count = 40
 # for documentaton on making checks asynchronous.
 async_health_check_thread_count = 0
 
+
```
Comment (jkinkead) [inline xrpc/src/main/resources/com/nordstrom/xrpc/xrpc.conf]: Remove extra newline?
